import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/section/header/Header";
import Footer from "./components/section/footer/Footer";
import data from "@/data/data.json"
import { Inter } from "next/font/google";
import SmoothScroll from "./components/shared/SmoothScroll"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-primary",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SmoothScroll/>
        <Header data={data} topBar={data.topBar}/>
        {children}
        <Footer data={data}/>
        </body>
    </html>
  );
}
